on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Install dependencies
        run: npm install -g pnpm@latest && pnpm install
      - name: Run tests
        run: pnpm lint
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to production server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            source ~/.bashrc
            export PATH="$HOME/.nvm/versions/node/v24.14.0/bin:$PATH"
            cd live/
            git pull
            pnpm db:deploy
            pnpm run build
            pm2 restart all
          '
